apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  name: shared-cluster
  namespace: k3k-system
spec:
  mode: shared
  servers: 3
  persistence:
    type: ephemeral
  serverArgs:
    - --cluster-init
    - --disable=traefik